# |----------------------|
# | YetAnotherSignEditor |
# |     by TehBrian      |
# |   hope u enjoy <3    |
# |----------------------|
# |
# | Source Code: https://github.com/ItsTehBrian/BuildersUtilities
# | Feedback and Support: https://tehbrian.xyz/discord
# |

messages:
  no_permission: "&cI'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error."
  player_only: "&cOnly players can perform this command."
  edit:
    enabled: "&b Enabled sign editing. &7(Click on a sign while holding a sign.)"
    disabled: "&3 Disabled sign editing."
  color:
    enabled: "&d Enabled sign coloring. &7(Insert color codes into sign text.)"
    disabled: "&5 Disabled sign coloring."
  reload: "&c Successfully reloaded the config!"
  help:
    - "&7--- &fYetAnotherSignEditor &7---"
    - ""
    - "&a/yase"
    - "&7   Display this help message."
    - "&b/yase edit"
    - "&7   Toggle your ability to edit sign text."
    - "&d/yase color"
    - "&7   Toggle your ability to color sign text."
    - "&c/yase reload"
    - "&7   Reload the plugin's config."