name: YetAnotherSignEditor
description: ${description}
authors: [ TehBrian ]
website: https://github.com/TehBrian/YetAnotherSignEditor

version: ${version}
main: xyz.tehbrian.yetanothersigneditor.YetAnotherSignEditor
api-version: 1.18

permissions:
  yase.set:
    description: Permission to run /yase set.
    default: true
  yase.edit:
    description: Permission to edit sign text.
    default: true
  yase.color:
    description: Permission to color sign text.
    default: true
  yase.color.minimessage:
    description: Permission to use the MiniMessage format type.
    default: op
  yase.color.legacy:
    description: Permission to use the Legacy format type.
    default: true
  yase.reload:
    description: Permission to run /yase reload.
    default: op
