name: YetAnotherSignEditor
description: Easily edit signs, with support for both MiniMessage and legacy color codes.
authors: [ TehBrian ]
website: https://github.com/TehBrian/YetAnotherSignEditor

version: ${version}
main: xyz.tehbrian.yetanothersigneditor.YetAnotherSignEditor
api-version: 1.17

permissions:
  yase.edit:
    description: Permission to edit sign text.
    default: true
  yase.color:
    description: Permission to color sign text.
    default: true
  yase.reload:
    description: Permission to run /yase reload.
    default: op
