name: YetAnotherSignEditor
description: ${description}
authors: [ TehBrian ]
website: https://github.com/TehBrian/YetAnotherSignEditor

version: ${version}
main: dev.tehbrian.yetanothersigneditor.YetAnotherSignEditor
api-version: 1.20

permissions:
  yase.set:
    description: Permission to run /yase set.
    default: true
  yase.open:
    description: Permission to run /yase open.
    default: true
  yase.copy:
    description: Permission to run /yase copy.
    default: true
  yase.unwax:
    description: Permission to run /yase unwax.
    default: true
  yase.format:
    description: Permission to format sign text.
    default: true
  yase.format.minimessage:
    description: Permission to use the MiniMessage formatting type.
    default: op
  yase.format.legacy:
    description: Permission to use the legacy formatting type.
    default: true
  yase.reload:
    description: Permission to run /yase reload.
    default: op
